### ISSUE TITLE
Перемешивание массива

### ISSUE THREAD

**Issue by mezhmal** [Smak0ff/gitTask#1]
В своем решении вы используете функцию shuffle
https://github.com/Smak0ff/gitTask/blob/c8d3c30ad7fb69a282c4827164aed9bcde8452bc/task1.php#L15

Попробуйте повторить решение без использования этой функции. Каким образом вы перемешали бы числа в массиве самостоятельно?

**Comment by Smak0ff** [comment]
Получилось выполнить следующим образом: 
function randomArray(){
$num = rand(1,30);//Создаем произвольное число в диапозоне от 1 до 30
echo "Произвольное число: ".$num."<br>";
$arr = range(1,$num);//Создаем массив чисел от 1 до числа $num
$i=0;
do {//Запускаем цикл
$new = array_rand($arr,1);//Берем случайный элемент из массива $arr и передаем его в переменную $new
unset($arr[$new]);//Удаляем этот элемент из старого массива, чтобы числа, при обращении в старый массив не повоторялись
$newArr[] = $new;//Добавляем полученный элемент в новый массив
$i++;
} while ($i <= ($num-1));
print_r($newArr);
}

**Comment by mezhmal** [comment]
Хорошо. Предложенное решение вполне подходит для вашего уровня. В будущем с ростом опыта от вас будет ожидаться похожее решение, но без использования дополнительного массива, а потом ещё чуть изящнее - без использования дополнительной переменной $new для временного хранения числа.

**Comment by mezhmal** [comment]
Давайте для будущих решений использовать главную силу Гитхабе - версионирование кода. Попробуйте исправить ваше первоначальное решение в файле task1.php, сделать git commit, а затем git push в репозиторий. Это ежедневные действия в работе программиста, к ним нужно привыкнуть.

**Comment by Smak0ff** [comment]
Готово.
