### ISSUE TITLE
Валидация поля "Морского боя"

### ISSUE THREAD

**Issue by mezhmal** [Smak0ff/gitTask#2]
https://github.com/Smak0ff/gitTask/blob/c8d3c30ad7fb69a282c4827164aed9bcde8452bc/task3.php#L22

Хорошо. Здесь вы проверяете два предположения:
1) равна ли сумма клеток поля, занятых кораблями, двадцати?
2) не превышает ли сумма клеток в каждой строке поля восьми?

Очевидно, что этих проверок недостаточно.
Я предлагаю сейчас отказаться от использования классов и идей ООП и сосредоточиться на алгоритме проверки. Позже, когда разберемся с алгоритмом, можно будет повторить решение с использованием классов.

Попробуйте сформулировать словами, какие ещё проверки необходимо сделать, чтобы проверить корректность расстановки кораблей на поле?

**Comment by Smak0ff** [comment]
Необходимо выполнить проверку правильности составления кораблей(не должны быть Г-образными+проверить что состав кораблей правильный) и их правильность размещения на поле(минимум одна клетка пропуска между разными кораблями)

**Comment by mezhmal** [comment]
Получается, что нам необходимы такие дополнительные проверки:
1) не должны быть Г-образными;
2) состав кораблей правильный;
3) минимум одна клетка пропуска между разными кораблями.

Хорошо. Эта часть работы программиста - уметь из произвольного текста задачи выделить и  сформулировать условия выполнения программы. От умения формулировать для себя такие условия напрямую зависит сложность (или простота) и надёжность (или ненадежность) алгоритма твоего будушего решения.

Пока в нашем списке мне нравится третье условие.
В первом условии "не должны быть Г-образными" мы забываем, что для четырехпалубника могут быть и другие некорретные варианты.
Во втором условии "состав кораблей правильный" нам необходимо определить те самые условия. Правильный состав - это какой?

Поэтому давай уточнять условия проверок. Попробуй написать их более полно. Иначе мы рискуем в нашем алгоритме пропустить какой-нибудь некорретные вариант расстановки кораблей на поле и наши будущие игроки будут называть нас плохими словами 😀

**Comment by Smak0ff** [comment]
По поводу первого условия - да, под г-образными кораблями я имел в виду и квадратные четырехпалубники, и те, которые будут идти змейкой, и те, которые будут размещены по диагонали(это касается и двух и трехпалубников), не знаю почему не указал этого) Что касается второго условия, то под правильным составом я подразумевал то, что должно быть 4 однопалубных, 3 двухпалубных, 2 трехпалубных и 1 четырехпалубный корабль. Возможно стоит ещё проверить, что корабли не выходят за границы поля.

**Comment by Smak0ff** [comment]
> Как проверку правильности состава можно будет написать на языке программы?
С этим уже сложнее) Возможно в код программы нужно поместить переменные, в которых указан правильный состав кораблей, а далее будет выполняться сравнение кораблей из массива с этими самыми переменными.

**Comment by Smak0ff** [comment]
Мне на ум приходят только варианты вроде запуска цикла с перебором каждого элемента массива на проверки вроде:
if ($board[0][0]==1){
  if ($board[0][1]!=1 && $board[1][0]!=1 && $board[1][1]!=1){
   //Однопалубник
   $onePal++;
  }
  else if($board[0][1]==1 && $board[0][2]!=1 && $board[1][0]!=1 && $board[1][1]!=1){
   //Двухпалубник
   $twoPal++;
  } и так далее проверять все возможные варианты, вплоть до ошибочных, при которых сразу же идёт возврат ошибки. 
} 
По итогу должна быть проверка на то, что $onePal==4, $twoPal==6, $threePal==6, fourPal==4, но это выглядит слишком громоздкой конструкцией и я не уверен, что вообще смогу реализовать. Но могу попробовать, если я на правильном пути :)

**Comment by Smak0ff** [comment]
Ещё можно добавить в условия проверку количества свободных клеток. Оно также всегда неизменно,

**Comment by Smak0ff** [comment]
$a = 0;
$b = 0;
do {
  if ($board[$a][$b]==1){
    if ($board[$a][($b+1)]!=1 && $board[($a+1)][$b]!=1 && $board[($a+1)][($b+1)]!=1 && $board[($a-1)][($b+1)]!=1 && $board[($a-1)][($b)]!=1 && $board[($a-1)][($b-1)]!=1 && $board[($a)][($b-1)]!=1 && $board[($a+1)][($b-1)]!=1){
     $onePal++;
     $a++;
    }
    else if($board[$a][$b+1]==1 && $board[$a][($b+2)]!=1 && $board[($a+1)][$b]!=1 && $board[($a+1)][($b+1)]!=1 && $board[($a+1)][($b+2)]!=1....итд//так выполняем проверки на 1-2-3-4 палубники во все направления и на пустую точку(без корабля) с добавлением к $a++ в конце до значения "10", а на 10 переходим на следующую строчку добавляя $b++ и в конце закрываем цикл:
} while ($a < 10 && $b < 10);
В конце проверяем что $onePal==4, $twoPal==6, $threePal==6, fourPal==4
Всё должно работать, но выглядит, конечно, некрасиво. Если хотите - могу расписать до самого конца, просто потребуется время. Другое решение я пока что не придумал)

**Comment by Smak0ff** [comment]
$a = 0;
$b = 0;
do {
  if ($board[$a][$b]==1){
    if ($board[$a][($b+1)]!=1 && $board[($a+1)][$b]!=1 && $board[($a+1)][($b+1)]!=1 && $board[($a-1)][($b+1)]!=1 && $board[($a-1)][($b)]!=1 && $board[($a-1)][($b-1)]!=1 && $board[($a)][($b-1)]!=1 && $board[($a+1)][($b-1)]!=1){
     $onePal++;
     $a++;
    }
    else if($board[$a][$b+1]==1 && $board[$a][($b+2)]!=1 && $board[($a+1)][$b]!=1 && $board[($a+1)][($b+1)]!=1 && $board[($a+1)][($b+2)]!=1....итд//так выполняем проверки на 1-2-3-4 палубники во все направления и на пустую точку(без корабля) с добавлением к $a++ в конце до значения "10", а на 10 переходим на следующую строчку добавляя $b++ и возвращая $a=0. Так цикл доходит до $a=9, $b=9 и в конце цикл закрывается:
} while ($a < 10 && $b < 10);
Далее проверяем что $onePal==4, $twoPal==6, $threePal==6, fourPal==4
Всё должно работать, но выглядит, конечно, некрасиво. Если хотите - могу расписать до самого конца, просто потребуется время. Другое решение я пока что не придумал)

**Comment by mezhmal** [comment]
> По поводу первого условия - да, под г-образными кораблями я имел в виду и квадратные четырехпалубники, и те, которые будут идти змейкой, и те, которые будут размещены по диагонали(это касается и двух и трехпалубников), не знаю почему не указал этого)
Все это мы можем сократить до требования "сегменты кораблей должны быть расположены только на одной линии (по вертикали или по горизонтали)"

Для определения правильного состава ты предлагаешь считать количество кораблей. Это хорошее условие.

Наша задача хороша тем, что имеет множество решений.
Да, придуманное тобой решение не выглядит красивым. Получится слишком много кода, его будет трудно прочитать. Множественные логические операции могут запутать кого угодно. При этом в коде будут повторяться фрагменты, а это нарушение нашего главного принципа [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself).
Давай начнем размышлять, как его можно сократить.

**Comment by mezhmal** [comment]
Наверное наиболее простым способом решения будет представить себя на позиции игрока, который не видит поля противника и начинает последовательно, клетка за клеткой, искать корабли противника. Для этого мы будем использовать чистое поле, на котором будем ноликами отмечать промахи, а единичками попадания.

Как только у нас имеется попадание, нам нужно перестать двигаться "вслепую" и попытаться определить положение (вертикальное или горизонтальное) и длину корабля. Перед нами может однопалубник (если вокруг только нолики) или любой другой корабль. Функция определения длины корабля будет, пожалуй, самой сложной в нашем алгоритме. Найденный нами корабль мы, во-первых, нарисуем на нашем чистом поле, чтобы повторно им уже не заниматься, во-вторых, проверим, что его не касается никакой другой корабль (это запрещено условиями задачи), и, в-третьих, увеличим нужный счетчик кораблей ($onePal, $twoPal, $threePal или fourPal).

Подумай, можно ли как-то упростить такое решение?

**Comment by Smak0ff** [comment]
Всё будет начинаться с такого же цикла как и ранее, до момента попадания на точку с кораблём. Далее, при попадании на точку со значением 1, мы будем запускать функцию проверки соседних по вертикали(вверх и вниз) и горизонтали(влево и вправо) точек и на каждой из них, в добавок, будем запускать функцию проверки точек вокруг неё, чтобы исключить возможность соприкосновения с другими кораблями. Затем все эти значения будут записываться в переменные $onePal, $twoPal, $threePal или $fourPal. Так код станет более читабельным.

**Comment by Smak0ff** [comment]
Завтра у меня рабочий день, но достаточно свободный. Постараюсь в течение дня реализовать всё на практике.

**Comment by Smak0ff** [comment]
Признаюсь честно - я в замешательстве. 
https://github.com/Smak0ff/gitTask/blob/master/task33.php  - здесь выложил валидатор. Я никак не могу его запустить. При запуске проверки ему становится плохо и через 180 секунд срабатывает таймаут. По моему представлению всё должно работать, и это я ещё не запускаю проверку вокруг кораблей, в которые попали, думал может там какая-то путаница происходит или слишком сильно нагружаю сервер вычислениями). Прошу помощи в решении, самостоятельно найти ошибку не получается.

**Comment by Smak0ff** [comment]
Сергей, сегодня днём звонил номер городской (+78632012822), к сожалению телефона под рукой не было и не смог взять трубку. Насколько я понял - из вашей компании, перезвонил - сказали, что многоканальный номер и информацией не располагают. У вас были какие-то вопросы или по поводу задания?

**Comment by mezhmal** [comment]
Станислав, прошу прощения. Я на ближайшие пару дней буду вынужден прервать обсуждение. В четверг вернусь, посмотрю на твое решение.
Зачем тебе звонили я не знаю. Если это какой-то важный вопрос - обязательно перезвонят. Вряд ли это как-то связано с заданием.

**Comment by Smak0ff** [comment]
Хорошо, до четверга
